### PR TITLE
Fix some files License header

### PR DESCRIPTION
**Pull request by CalvinKirs**
todo:Pay attention to dual protocol files under config

### CODE REVIEW

**Comment by zhongjiajie** [comment]
It seem your target branch is master?

**Comment by CalvinKirs** [comment]
> It seem your target branch is master?

We need to maintain two branches. master&dev

**Comment by zhongjiajie** [comment]
Oh, I forgot  this point, thank for clarification. 👍

**Comment by CalvinKirs** [comment]
> Oh, I forgot this point, thank for clarification. 👍

Thx,PTAL

**Comment by leo65535** [comment]
hi @CalvinKirs, I have a question is the following version correspondence correct?
master: 1.x
dev: 2.x

**Comment by CalvinKirs** [comment]
> 

yup, you are right

**Comment by CalvinKirs** [comment]
> hi @CalvinKirs, I have a question is the following version correspondence correct? master: 1.x dev: 2.x

yup, you are right.

**Review by zhongjiajie — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
