### PR TITLE
[Feat] maven dependency optimization #760

### PR DESCRIPTION
**Pull request by wolfboys**
maven dependency optimization

1. Improve maven dependencies, extract some common plugins (e.g: scala-maven-plugin) put them in the parent, and the submodules are not declared.

2. plugins related to `maven-deploy-plugin` are removed, because they will affect other developers' packaging and compilation 

3. Standardize the declaration of all submodules ```<parent>```, before:

```
<parent>
<artifactId>seatunnel</artifactId>
<groupId>io.github.interestinglab.seatunnel</groupId>
<version>2.0.4</version>
</parent>
```

after:

```
<parent>
<groupId>io.github.interestinglab.seatunnel</groupId>
<artifactId>seatunnel</artifactId>
<version>2.0.4</version>
</parent>
```

In case of existing issue, reference it using one of the following:
closes: #760
related: #760

Here is some example about how to write a good git commit message:
http://chris.beams.io/posts/git-commit/
-->

---

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by wolfboys** [comment]
@garyelephant @CalvinKirs  PTAL.

**Review by dailidong — APPROVED** [review]
+1
good job

**Comment by yx91490** [comment]
It seems that scala-maven-plugin was removed from parent pom on purpose in https://github.com/InterestingLab/seatunnel/commit/e261f7571dc48e1267ff5c3f296d0737bbd314ce. the core module will be purge java code in the future, so I think  we'd better not to raise it.

**Comment by wolfboys** [comment]
@yx91490 thx, I found that many modules coexist with java and scala. The `scala-maven-plugin` is declared under these submodules. if move the scala-maven-plugin into the parent, after the scala code is converted to java, just remove the scala-maven-plugin in the parent, and other submodules do not need to be modified,  it seems to be a good practice, no matter what, either way, this is not a big problem.

**Comment by yx91490** [comment]
> after the scala code is converted to java, just remove the scala-maven-plugin in the parent, and other submodules do not need to be modified

maybe not, If you raise the scala-maven-plugin to parent then remove, all submodules need to add the plugin into their pom.xml again.

**Comment by wolfboys** [comment]
when we converted scala code to the java done, just removed scala plugin in parent module。at this time we don't need scala plugin. Why should we define scale plugin it in the submodule?

**Comment by wolfboys** [comment]
> > after the scala code is converted to java, just remove the scala-maven-plugin in the parent, and other submodules do not need to be modified
> 
> 
> 
> maybe not, If you raise the scala-maven-plugin to parent then remove, all submodules need to add the plugin into their pom.xml again.

when we converted scala code to the java done, just removed scala plugin in parent module。at this time we don't need scala plugin. Why should we define scale plugin it in the submodule?

**Review by leo65535 — APPROVED** [review]
+1, from my side.

**Comment by CalvinKirs** [comment]
> > after the scala code is converted to java, just remove the scala-maven-plugin in the parent, and other submodules do not need to be modified
> 
> maybe not, If you raise the scala-maven-plugin to parent then remove, all submodules need to add the plugin into their pom.xml again.

It ok be declared in the root pom, and there is no need to add a redundant configuration to the sub-module.

**Pull request merged**
