### PR TITLE
[Refactor][Connector] Put source and sink into combined connector

### PR DESCRIPTION
**Pull request by zixi0825**
## Purpose of this pull request

 This pull request put source and sink into combined connector #824

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by zixi0825** [comment]
@CalvinKirs

**Comment by cody1993** [comment]
The new connector name is more friendly, 👍

**Comment by garyelephant** [comment]
@zixi0825 Hi, please resolve the conflicts as above, then I will merge

**Review by garyelephant — APPROVED** [review]
Thanks for your contribution

**Pull request merged**
