### PR TITLE
[SeaTunnel #688] Support define variables

### LINKED ISSUE #688: [Feature][Configuration] Support define variables
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The v2 branch is not support variables substitution now.

https://github.com/InterestingLab/seatunnel/blob/master/config/variable-substitution.conf.template

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request
closes #688 
Support define variables

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by simon824** [comment]
cc @garyelephant @CalvinKirs

**Comment by CalvinKirs** [comment]
Thx for your contributions, can you provide UT?

**Comment by simon824** [comment]
> Thx for your contributions, can you provide UT?

Done, take a review when you are free, thx.

**Comment by garyelephant** [comment]
@simon824 Hi, typesafe config has builtin variable substitution feature, so we don't need to implement again,  the only thing we need to do is integrating this feature to v2 codebase, just like v1 codebase. Please refer to v1 codebase if you are not sure about this. I will close this PR, thanks

**Pull request closed without merging**
