### PR TITLE
Fix throw ClassCastException when submit app to flink1.9.3

### PR DESCRIPTION
**Pull request by leo65535**
---

## Purpose of this pull request

Fix https://github.com/InterestingLab/seatunnel/issues/717

```log
[dcadmin@dcadmin seatunnel-dist-2.0.4-2.11.8]$ bin/start-seatunnel-flink.sh 
Starting execution of program
[INFO] Loading config file: /work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.4-2.11.8/config/application.conf
[INFO] parsed config file: {
    "env" : {
        "execution.parallelism" : 1
    },
    "source" : [
        {
            "result_table_name" : "fake",
            "plugin_name" : "FakeSourceStream",
            "field_name" : "name,age"
        }
    ],
    "transform" : [
        {
            "plugin_name" : "sql",
            "sql" : "select name,age from fake"
        }
    ],
    "sink" : [
        {
            "plugin_name" : "ConsoleSink"
        }
    ]
}

       *#*      *##*      *#*                                                           ##                                                      
       *#*      *##*      *#*                 ##                                        ##                                                      
       *#*     ****#*     *#*                 ##                                        ##                                                      
       *#*     *#**#*     *#*                 ##                                        ##                                                      
        *#*    *#**#*    *#*                  ##                                        ##                                                      
        *#*    *#**#*    *#*    ********    ########    ********     ## *****   ******* ##    ## *****   ********     ## *******                
        *#*   ********   *#*    ########*   ########   **#######*    ##*####*  **######*##    ##*####*  **######**    ##*######**               
        *#*   *#*  *#*   *#*    **** ***#*    ##      **#*** *****   ###***   **#******###    ###***   **#******#**   ###******#**              
         *#*  *#*  *#*  *#*            *#*    ##      *#*      *#*   ##*      *#**    **##    ##*      *#**    **#*   ##**    **#*              
         *#*  *#*  *#*  *#*            *#*    ##      *#*      *#*   ##*      *#*      *##    ##*      *#*      *#*   ##*      *#*              
         *#*  *#*  *#*  *#*     *****####*    ##      *#******###*   ##*      *#*      *##    ##*      *#*      *#*   ##*      *#*              
         *#* *#*    *#* *#*    **#########    ##      *###########   ##       ##        ##    ##       ##        #*   ##        #*              
         **#**#*    *#**#*     *#****   ##    ##      *#*            ##       *#*      *##    ##       *#*      *#*   ##*      *#*              
          *#**#*    *#**#*     *#*     *##    ##      *#*            ##       *#*      *##    ##       *#*      *#*   ##*      *#*              
          *#**#*    *#**#*     *#*     *##    *#*     *#**           ##       *#**    **##    ##       *#**    **#*   ##**    **#*              
          *#*#*      *#*#*     *#** ***###    *#**    **#*** ****    ##       **#******###    ##       **#******#**   ###******#**              
          **##*      *##**     **######*##    *#####   **########    ##        **######*##    ##        **######**    ##*######**               
           *##*      *##*       ******* ##     ***##    ****#****    ##         ******* ##    ##         ********     ## *******                
                                                                                                                      ##                        
                                                                                                                      ##                        
                                                                                                                      ##                        
                                                                                                                      ##                        
                                                                                                                      **                        


===============================================================================


Fatal Error, 

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: Unable to instantiate java compiler

Exception StackTrace: java.lang.IllegalStateException: Unable to instantiate java compiler
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:434)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.load3(JaninoRelMetadataProvider.java:375)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.lambda$static$0(JaninoRelMetadataProvider.java:109)
        at org.apache.flink.calcite.shaded.com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:149)
        at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at org.apache.flink.calcite.shaded.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.create(JaninoRelMetadataProvider.java:475)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.revise(JaninoRelMetadataProvider.java:488)
        at org.apache.calcite.rel.metadata.RelMetadataQuery.revise(RelMetadataQuery.java:193)
        at org.apache.calcite.rel.metadata.RelMetadataQuery.getPulledUpPredicates(RelMetadataQuery.java:797)
        at org.apache.calcite.rel.rules.ReduceExpressionsRule$ProjectReduceExpressionsRule.onMatch(ReduceExpressionsRule.java:299)
        at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:319)
        at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:560)
        at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:419)
        at org.apache.calcite.plan.hep.HepPlanner.executeInstruction(HepPlanner.java:256)
        at org.apache.calcite.plan.hep.HepInstruction$RuleInstance.execute(HepInstruction.java:127)
        at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:215)
        at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:202)
        at org.apache.flink.table.plan.Optimizer.runHepPlanner(Optimizer.scala:228)
        at org.apache.flink.table.plan.Optimizer.runHepPlannerSequentially(Optimizer.scala:194)
        at org.apache.flink.table.plan.Optimizer.optimizeNormalizeLogicalPlan(Optimizer.scala:150)
        at org.apache.flink.table.plan.StreamOptimizer.optimize(StreamOptimizer.scala:65)
        at org.apache.flink.table.planner.StreamPlanner.translateToType(StreamPlanner.scala:410)
        at org.apache.flink.table.planner.StreamPlanner.org$apache$flink$table$planner$StreamPlanner$$translate(StreamPlanner.scala:182)
        at org.apache.flink.table.planner.StreamPlanner$$anonfun$translate$1.apply(StreamPlanner.scala:127)
        at org.apache.flink.table.planner.StreamPlanner$$anonfun$translate$1.apply(StreamPlanner.scala:127)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.flink.table.planner.StreamPlanner.translate(StreamPlanner.scala:127)
        at org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.toDataStream(StreamTableEnvironmentImpl.java:319)
        at org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.toRetractStream(StreamTableEnvironmentImpl.java:264)
        at io.github.interestinglab.waterdrop.flink.util.TableUtil.tableToDataStream(TableUtil.java:39)
        at io.github.interestinglab.waterdrop.flink.transform.Sql.processStream(Sql.java:45)
        at io.github.interestinglab.waterdrop.flink.stream.FlinkStreamExecution.start(FlinkStreamExecution.java:61)
        at io.github.interestinglab.waterdrop.Waterdrop.entryPoint(Waterdrop.java:117)
        at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:74)
        at io.github.interestinglab.waterdrop.WaterdropFlink.main(WaterdropFlink.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:604)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:466)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
        at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
        at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1008)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1081)
        at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1081)
Caused by: java.lang.ClassCastException: org.codehaus.janino.CompilerFactory cannot be cast to org.codehaus.commons.compiler.ICompilerFactory
        at org.codehaus.commons.compiler.CompilerFactoryFactory.getCompilerFactory(CompilerFactoryFactory.java:129)
        at org.codehaus.commons.compiler.CompilerFactoryFactory.getDefaultCompilerFactory(CompilerFactoryFactory.java:79)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:432)
        ... 61 more
```

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by leo65535** [comment]
20335d5fac6763d3fd4e22ac6ffdc7a

**Comment by CalvinKirs** [comment]
hi, thank you for your contribution, can you resolve the conflicting files first

**Comment by leo65535** [comment]
> hi, thank you for your contribution, can you resolve the conflicting files first

Done.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
