### PR TITLE
[v1] added the abstraction of BaseAction

### PR DESCRIPTION
**Pull request by garyelephant**
## Purpose of this pull request

  Define an action to do whatever you want on execution started or finished,
  the sequence will be as follows:
```
      program started ..
      BaseAction::onExecutionStarted()
        for loop for data:
          Source --> Transform --> Sink
      BaseAction::onExecutionFinished()
      program finished ..
 ```

  Attention:
    1. For now, this only apply for batch processing, not for streaming or structured streaming processing

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Review by wntp — COMMENTED** [review]
very good，I think this implementation is currently the most lightweight

**Review by wntp — APPROVED** [review]
This would be a great feature

**Review by RickyHuo — APPROVED** [review]
LGTM

**Comment by RickyHuo** [comment]
maybe this would be better ?

```
void onExecutionFinished(SparkSession session, SparkConf sparkConf, Config config);
```

**Pull request merged**
