### PR TITLE
[SeaTunnel #813] [ctl] Introduce jcommander framework to seatunnel project

### LINKED ISSUE #813: [Feature][ctl] Introduce jcommander framework to seatunnel project
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, the seatunnel-core-base module is hard to scale inclusing(parse the args, add new command),

Here, introduce jcommander framework to replace `scopt`, https://jcommander.org/
- JCommander is an annotation-based library for parsing command-line parameters
- With JCommander, we can offload tricky tasks such as parsing, validation, and type conversions, to allow us to focus on our logic.
- `scopt` is written by scala, we can not use it in java.
- JCommander is released under the Apache 2.0 license.

```
class TestCommand {
    @Parameter(names={"--length", "-l"})
    int length;
    @Parameter(names={"--size", "-s"})
    int size;
}
```

### Related issues

#798

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leo65535**
## Purpose of this pull request

Fixed #813 

Currently, the seatunnel-core-base module is hard to scale inclusing(parse the args, add new command),

Here, introduce jcommander framework to replace `scopt`, https://jcommander.org/
- JCommander is an annotation-based library for parsing command-line parameters
- With JCommander, we can offload tricky tasks such as parsing, validation, and type conversions, to allow us to focus on our logic.
- `scopt` is written by scala, we can not use it in java.
- JCommander is released under the Apache 2.0 license.

```
class TestCommand {
    @Parameter(names={"--length", "-l"})
    int length;
    @Parameter(names={"--size", "-s"})
    int size;
}
```

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by leo65535** [comment]
hi @garyelephant @CalvinKirs take a review when you are free, thanks.

**Review by wuchunfu — COMMENTED** [review]
LGTM

**Comment by garyelephant** [comment]
Nice work, I will check at this weekend.

**Comment by cody1993** [comment]
+1, LGTM too.

**Comment by superguhua** [comment]
LGTM

**Comment by leo65535** [comment]
cc @CalvinKirs, I add `0` to `.dlc.json` file.

```
FILE: ./seatunnel-config/README.md
  [✖] https://github.com/ElderResearch/ssc


  ERROR: 1 dead links found!
  95 links checked.
  [✖] https://github.com/ElderResearch/ssc → Status: 0
Error: Process completed with exit code 1.
```

**Review by garyelephant — APPROVED** [review]
nice work, thanks

**Pull request merged**
