### PR TITLE
[SeaTunnel #747][plugin] Add apache-rat-plugin

### LINKED ISSUE #747: [Feature][plugin] Add apache-rat-plugin
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We can add `apache-rat-plugin` plugin which can help us check the file license.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leo65535**
## Purpose of this pull request

Fixed #747 

We can add `apache-rat-plugin` plugin which can help us check the file license.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by leo65535** [comment]
cc @CalvinKirs, the same thing like what you did https://github.com/InterestingLab/seatunnel/pull/746,
we can use `apache-rat-plugin` to help use check the files automatically.

**Comment by CalvinKirs** [comment]
> cc @CalvinKirs, the same thing like what you did #746, we can use `apache-rat-plugin` to help use check the files automatically.

Thank you for your contribution. In fact, we have used sky-walking-eyes for detection, which is more robust than RAT. in addition. META-INF does not need to increase the license header.

**Comment by leo65535** [comment]
Nice, `sky-walking-eyes` is a new choice for me. BTW, `apache-rat-plugin` can help us check rat locally, when we execute `mvn` command, it will check the license.

> META-INF does not need to increase the license header.

ok, but most apache projects already add license header to `META-INF`, like spark、flink etc.

**Comment by CalvinKirs** [comment]
> Nice, `sky-walking-eyes` is a new choice for me. BTW, `apache-rat-plugin` can help us check rat locally, when we execute `mvn` command, it will check the license.
In fact, if necessary, you can use skywalking-eyes detection, which is also very convenient. In addition, we have also added detection in CI, and the rat is a bit redundant.
> 
> > META-INF does not need to increase the license header.
> 
> ok, but most apache projects already add license header to `META-INF`, like spark、flink etc.
Ok, let's keep it, but it is not necessary.

**Comment by leo65535** [comment]
Make sense. Got, let's close it first, open it when necessary, thanks.

**Pull request closed without merging**
