### PR TITLE
[Feature#715] add quick-start Dockerfile

### PR DESCRIPTION
**Pull request by yx91490**
closes: #715 
---

## Purpose of this pull request

add quick-start Dockerfile

## Check list

* [X] Code changed are covered with tests, or it does not need tests for reason:
* [X] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by yx91490** [comment]
Please merge #737 first, or will throw error when running.

**Comment by garyelephant** [comment]
+1, very nice feature, according to my own test, I think we can do more things based on this:
* tell users to execute mvn package command in the root dir of seatunnel project in seatunnel-dist/docker/README.md
* reduce size of docker image, currently it's 1.5GB
* make mvn package more faster if possible
* push this image to dockerhub after we are in apache incubator. (@CalvinKirs Can you do this?)

**Comment by CalvinKirs** [comment]
> +1, very nice feature, according to my own test, I think we can do more things based on this:
> 
> * tell users to execute mvn package command in the root dir of seatunnel project in seatunnel-dist/docker/README.md
> * reduce size of docker image, currently it's 1.5GB
> * make mvn package more faster if possible

> * push this image to dockerhub after we are in apache incubator, add some document for user to easy get started with this docker image in _getting started page_ of user manual (@CalvinKirs Can you do this?)
well, give it to me.

**Comment by kezhenxu94** [comment]
For quick start, I'd provide a docker compose to orchestrate the needed components like Spark and SeaTunnel instead of packaging them all together inside a single Docker image, that will hide the users from how the components work individually. Also we don't bother to maintain the codes (Dockerfile) to download / package other third party components (Spark, Flink, etc.)

**Comment by yx91490** [comment]
> +1, very nice feature, according to my own test, I think we can do more things based on this:
> 
> * tell users to execute mvn package command in the root dir of seatunnel project in seatunnel-dist/docker/README.md
> * reduce size of docker image, currently it's 1.5GB
> * make mvn package more faster if possible
> * push this image to dockerhub after we are in apache incubator, add some document for user to easy get started with this docker image in _getting started page_ of user manual (@CalvinKirs Can you do this?)

done

**Comment by garyelephant** [comment]
@yx91490 nice work

**Review by garyelephant — APPROVED** [review]
nice work

**Pull request merged**
