### PR TITLE
[Feature][plugin-spark-sink-mysql] Change plugin-spark-sink-mysql to plugin-spark-sink-jdbc

### PR DESCRIPTION
**Pull request by wuchunfu**
## Purpose of this pull request

[Feature][plugin-spark-sink-mysql] Change plugin-spark-sink-mysql to plugin-spark-sink-jdbc #825
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
Overall it looks good, but can we unify the naming format of the configuration files?

**Comment by RickyHuo** [comment]
The related docs should move to https://github.com/InterestingLab/seatunnel-docs

**Comment by CalvinKirs** [comment]
> The related docs should move to https://github.com/InterestingLab/seatunnel-docs

The documentation will be migrated to the code base later. @wuchunfu Doing this work

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
