### PR TITLE
Remove Chinese comment in flink-api pom.xml

### PR DESCRIPTION
**Pull request by zhongjiajie**
---

## Purpose of this pull request

Remove Chinese comment in flink-api pom.xml

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason: pom.xml change
* [x] Change does not need document change

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I find out we already have Chinese check in https://github.com/InterestingLab/seatunnel/blob/7703be091f57db918ff463a482b908b14d56d02e/tools/checkstyle/checkStyle.xml#L43-L47. and I found default file filter is `java` in https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#includes.

I try to add `pom.xml` in section in https://github.com/InterestingLab/seatunnel/blob/2455218a1433deaa8b0798d5a6c07bf1a881ba41/pom.xml#L622-L633, but ckeckstyle still skip `pom.xml`. Am I miss something @kezhenxu94 
```xml
    <includes>
        **\/*.java,
        **/pom.xml
    <includes>
```

**Comment by kezhenxu94** [comment]
@zhongjiajie maven only checks source files in "maven" project, a.k.a `src`, files like `.asf.yaml`, `.github/` are not maven project resources thus won't be checked

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
> @zhongjiajie maven only checks source files in "maven" project, a.k.a `src`, files like `.asf.yaml`, `.github/` are not maven project resources thus won't be checked

Thanks for your explanation

**Comment by zhongjiajie** [comment]
> @zhongjiajie maven only checks source files in "maven" project, a.k.a `src`, files like `.asf.yaml`, `.github/` are not maven project resources thus won't be checked

Thanks for the clarification

**Pull request merged**
