### PR TITLE
[Feature #786] Introduce Scalafmt to auto format scala code

### LINKED ISSUE #786: [Feature] Introduce Scalafmt to auto format scala code
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Introduce Scalafmt to auto format scala code

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request

closes #786 
Introduce Scalafmt to auto format scala code

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by simon824** [comment]
cc @zhongjiajie @CalvinKirs

**Comment by CalvinKirs** [comment]
> cc @zhongjiajie @CalvinKirs

please check CI fail

**Comment by timothy1024** [comment]
we already working on convert scala to java, https://github.com/InterestingLab/seatunnel/issues/766

**Comment by simon824** [comment]
> we already working on convert scala to java, #766

Module `plugin-spark-*` still developed on scala, maybe we can remove it after all scala has been converted to java?

**Comment by CalvinKirs** [comment]
It seems better for plug-in modules to not restrict the language, WDYT? @timothy1024 @simon824

**Comment by simon824** [comment]
> It seems better for plug-in modules to not restrict the language, WDYT? @timothy1024 @simon824

There are still many prs using scala now, I think the language can be unrestricted in the early stage, and maybe unified convert them later.

**Comment by timothy1024** [comment]
hi @simon824, I think these format codes are very good, but still think we should introduce `scalafmt`.

**Comment by zhongjiajie** [comment]
> It seems better for plug-in modules to not restrict the language, WDYT? @timothy1024 @simon824

I agree with that, some developers maybe love scala better than java

**Comment by zhongjiajie** [comment]
> hi @simon824, I think these format codes are very good, but still think we should not introduce `scalafmt`.

Do you have another way to format our code? And why not `scalafmt`? So sorry about that cause I am not familiar with scala

**Comment by timothy1024** [comment]
hi, we had discussed about `scala or java` in wechat, and already decided to remove scala.

**Comment by CalvinKirs** [comment]
> hi, we had discussed about `scala or java` in wechat, and already decided to remove scala.

This is not an open process (WeChat), we should at least reflect it in the issue or mail list.

**Comment by timothy1024** [comment]
> This is not an open process (WeChat), we should at least reflect it in the issue or mail list.

ok, I think we should use mail list / slack later, and should not use wechat group. wechat is not friendly for open source.

**Comment by CalvinKirs** [comment]
back to this question, I think we can introduce scala-format, uniform code format and style are important.

**Comment by zhongjiajie** [comment]
> back to this question, I think we can introduce scala-format, uniform code format and style are important.

Agree with that, I think unless we totally remove scala or just in plugin scope, otherwise keep code in format is a good idea.

**Comment by leo65535** [comment]
> Agree with that, I think unless we totally remove scala or just in plugin scope, otherwise keep code in format is a good idea.

+1

**Comment by timothy1024** [comment]
> Agree with that, I think unless we totally remove scala or just in plugin scope, otherwise keep code in format is a good idea.

+1, sounds resonable, thanks.

**Pull request closed without merging**
