### PR TITLE
Add code style check and fix some bad code

### PR DESCRIPTION
**Pull request by CalvinKirs**

### CODE REVIEW

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks and what a big change for codebase 👍

**Comment by yx91490** [comment]
is the codeStyle.xml in the root directory duplicated?

**Comment by zhongjiajie** [comment]
@yx91490 as @CalvinKirs said,  `root/codeStyle.xml` is for idea hint and formatter, and `checkStyle` for our CI process. But in dolphin scheduler we have PR to unify them in PR https://github.com/apache/dolphinscheduler/pull/6432

**Comment by yx91490** [comment]
> @yx91490 as @CalvinKirs said, `root/codeStyle.xml` is for idea hint and formatter, and `checkStyle` for our CI process. But in dolphin scheduler we have PR to unify them in PR [apache/dolphinscheduler#6432](https://github.com/apache/dolphinscheduler/pull/6432)

so we can remove it?

**Comment by CalvinKirs** [comment]
> > @yx91490 as @CalvinKirs said, `root/codeStyle.xml` is for idea hint and formatter, and `checkStyle` for our CI process. But in dolphin scheduler we have PR to unify them in PR [apache/dolphinscheduler#6432](https://github.com/apache/dolphinscheduler/pull/6432)
> 
> so we can remove it?

This has two different functions.

**Comment by zhongjiajie** [comment]
> so we can remove it?

I am not pretty sure about that, maybe we should ask @CalvinKirs for clarification.

**Pull request merged**
