### PR TITLE
[hotfix] fix wrong seatunnel-api dependency

### PR DESCRIPTION
**Pull request by leo65535**
## Purpose of this pull request

We had changed the seatunnel-api structure, this patch fixed these wrong dependencies. 

For more, please go to https://github.com/InterestingLab/seatunnel/pull/796

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by leo65535** [comment]
cc @garyelephant @CalvinKirs

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
CI passed yesterday seems to be because there is no update downstream ：）

**Comment by leo65535** [comment]
> CI passed yesterday seems to be because there is no update downstream ：）

you are right.

**Pull request merged**
